[Unit]
OnFailure=alert-telegram@%n.service
StartLimitIntervalSec=600
StartLimitBurst=20
[Service]
Restart=always
RestartSec=5
KillMode=mixed
KillSignal=SIGTERM
TimeoutStopSec=20
ExecStopPost=/bin/sleep 3
